[package]
name = "hello_rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1          # Slight optimisation but still quick builds
debug = true           # Keep full debug symbols
overflow-checks = true # Panic on integer overflow

[profile.release]
opt-level = 3          # Max optimisation
lto = true             # Link-Time Optimisation
codegen-units = 1      # Better optimisation, slower build
panic = "abort"        # Smaller binary, less panic info


[dependencies]
